In [5]:
#!/usr/bin/env python
# coding: utf-8

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

df = pd.read_csv('heart_disease_data.csv', header = 0)

x = np.array(df.iloc[:,0:10])
y = np.array(df['num'])

from sklearn import svm
svc = svm.SVC(kernel = 'linear')

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

accuracy, precision, recall = list(), list(), list()

for i in range(20):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33)
    
    scaler = StandardScaler()
    scaler.fit(x_train)
    x_train = scaler.transform(x_train)
    x_test = scaler.transform(x_test)
    
    svc.fit(x_train, y_train)
    y_pred = svc.predict(x_test)
    print(confusion_matrix(y_test, y_pred))

    accuracy.append(accuracy_score(y_test, y_pred))
    precision.append(precision_score(y_test, y_pred, pos_label = 1))
    recall.append(recall_score(y_test, y_pred, pos_label = 1))
    print(classification_report(y_test, y_pred))

print('accuracy = ', accuracy, end = '\n\n')
print('precision = ', precision, end = '\n\n')
print('recall = ', recall, end = '\n\n')

print(np.array(accuracy).mean(), np.array(precision).mean(), np.array(recall).mean())

[[93 13]
 [12 68]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.88       106
           1       0.84      0.85      0.84        80

    accuracy                           0.87       186
   macro avg       0.86      0.86      0.86       186
weighted avg       0.87      0.87      0.87       186

[[82 14]
 [21 69]]
              precision    recall  f1-score   support

           0       0.80      0.85      0.82        96
           1       0.83      0.77      0.80        90

    accuracy                           0.81       186
   macro avg       0.81      0.81      0.81       186
weighted avg       0.81      0.81      0.81       186

[[90 14]
 [22 60]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       104
           1       0.81      0.73      0.77        82

    accuracy                           0.81       186
   macro avg       0.81      0.80      0.80       186
weighted avg     

In [7]:
#!/usr/bin/env python
# coding: utf-8

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

df = pd.read_csv('heart_disease_data.csv', header = 0)

x = np.array(df.iloc[:,0:10])
y = np.array(df['num'])

from sklearn import svm
svc = svm.SVC(kernel = 'poly', degree = 3)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

accuracy, precision, recall = list(), list(), list()

for i in range(20):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33)
    
    scaler = StandardScaler()
    scaler.fit(x_train)
    x_train = scaler.transform(x_train)
    x_test = scaler.transform(x_test)
    
    svc.fit(x_train, y_train)
    y_pred = svc.predict(x_test)
    print(confusion_matrix(y_test, y_pred))

    accuracy.append(accuracy_score(y_test, y_pred))
    precision.append(precision_score(y_test, y_pred, pos_label = 1))
    recall.append(recall_score(y_test, y_pred, pos_label = 1))
    print(classification_report(y_test, y_pred))

print('accuracy = ', accuracy, end = '\n\n')
print('precision = ', precision, end = '\n\n')
print('recall = ', recall, end = '\n\n')

print(np.array(accuracy).mean(), np.array(precision).mean(), np.array(recall).mean())

[[82 14]
 [18 72]]
              precision    recall  f1-score   support

           0       0.82      0.85      0.84        96
           1       0.84      0.80      0.82        90

    accuracy                           0.83       186
   macro avg       0.83      0.83      0.83       186
weighted avg       0.83      0.83      0.83       186

[[79 12]
 [29 66]]
              precision    recall  f1-score   support

           0       0.73      0.87      0.79        91
           1       0.85      0.69      0.76        95

    accuracy                           0.78       186
   macro avg       0.79      0.78      0.78       186
weighted avg       0.79      0.78      0.78       186

[[75 17]
 [24 70]]
              precision    recall  f1-score   support

           0       0.76      0.82      0.79        92
           1       0.80      0.74      0.77        94

    accuracy                           0.78       186
   macro avg       0.78      0.78      0.78       186
weighted avg     

In [9]:
#!/usr/bin/env python
# coding: utf-8

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk

df = pd.read_csv('heart_disease_data.csv', header = 0)

x = np.array(df.iloc[:,0:10])
y = np.array(df['num'])

from sklearn import svm
svc = svm.SVC(kernel = 'rbf')

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

accuracy, precision, recall = list(), list(), list()

for i in range(20):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33)
    
    scaler = StandardScaler()
    scaler.fit(x_train)
    x_train = scaler.transform(x_train)
    x_test = scaler.transform(x_test)
    
    svc.fit(x_train, y_train)
    y_pred = svc.predict(x_test)
    print(confusion_matrix(y_test, y_pred))

    accuracy.append(accuracy_score(y_test, y_pred))
    precision.append(precision_score(y_test, y_pred, pos_label = 1))
    recall.append(recall_score(y_test, y_pred, pos_label = 1))
    print(classification_report(y_test, y_pred))

print('accuracy = ', accuracy, end = '\n\n')
print('precision = ', precision, end = '\n\n')
print('recall = ', recall, end = '\n\n')

print(np.array(accuracy).mean(), np.array(precision).mean(), np.array(recall).mean())

[[82 25]
 [20 59]]
              precision    recall  f1-score   support

           0       0.80      0.77      0.78       107
           1       0.70      0.75      0.72        79

    accuracy                           0.76       186
   macro avg       0.75      0.76      0.75       186
weighted avg       0.76      0.76      0.76       186

[[81 16]
 [28 61]]
              precision    recall  f1-score   support

           0       0.74      0.84      0.79        97
           1       0.79      0.69      0.73        89

    accuracy                           0.76       186
   macro avg       0.77      0.76      0.76       186
weighted avg       0.77      0.76      0.76       186

[[79 14]
 [27 66]]
              precision    recall  f1-score   support

           0       0.75      0.85      0.79        93
           1       0.82      0.71      0.76        93

    accuracy                           0.78       186
   macro avg       0.79      0.78      0.78       186
weighted avg     